version: 0.2

env:
  shell: bash
  variables:
    DOCKER_BUILDKIT: 1
    AWS_DEFAULT_REGION: ap-northeast-1
    AWS_ACCOUNT_ID: 643788824189
    # IMAGE_REPO_URL: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
    IMAGE_REPO_URL: 643788824189.dkr.ecr.ap-northeast-1.amazonaws.com
    IMAGE_REPO_NAME: hogeyama/nnu

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${IMAGE_REPO_URL}
  pre_build:
    commands:
      - docker build --cache-from=${IMAGE_REPO_URL}/${IMAGE_REPO_NAME}:dependency --build-arg BUILDKIT_INLINE_CACHE=1 -t ${IMAGE_REPO_NAME}:dependency --target dependency .
      - docker tag ${IMAGE_REPO_NAME}:dependency ${IMAGE_REPO_URL}/${IMAGE_REPO_NAME}:dependency
      - docker push ${IMAGE_REPO_URL}/${IMAGE_REPO_NAME}:dependency
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --cache-from=${IMAGE_REPO_NAME}:dependency --build-arg BUILDKIT_INLINE_CACHE=1 -t ${IMAGE_REPO_NAME}:latest .
      - docker tag ${IMAGE_REPO_NAME}:latest ${IMAGE_REPO_URL}/${IMAGE_REPO_NAME}:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:latest
