version: 0.2

env:
  shell: bash
  variables:
    DOCKER_BUILDKIT: 1
    AWS_ACCOUNT_ID: 643788824189
    PUBLIC_ECR_URL: public.ecr.aws/q3v2w3q5
    IMAGE_REPO_NAME: hogeyama/nnu
  parameter-store:
    DOCKERHUB_USERNAME: "/DockerHub/Username"
    DOCKERHUB_PASSWORD: "/DockerHub/Password"

phases:
  install:
    commands:
      - echo Installing AWS CLI v2...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - ./aws/install --update --bin-dir /root/.pyenv/shims
      - echo Logging in to Docker Hub...
      - docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD} "https://index.docker.io/v1/"
      - echo Logging in to Amazon ECR...
      - >
        aws ecr get-login-password --region ${AWS_DEFAULT_REGION}
        | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - >
        aws ecr-public get-login-password --region us-east-1
        | docker login --username AWS --password-stdin ${PUBLIC_ECR_URL}
  pre_build:
    commands:
      - echo Updating dependency image...
      - >
        docker build
        --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:dependency
        --build-arg BUILDKIT_INLINE_CACHE=1
        --tag ${IMAGE_REPO_NAME}:dependency
        --target dependency
        .
      - docker tag ${IMAGE_REPO_NAME}:dependency ${PUBLIC_ECR_URL}/${IMAGE_REPO_NAME}:dependency
      - docker push ${PUBLIC_ECR_URL}/${IMAGE_REPO_NAME}:dependency
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - >
        docker build
        --cache-from ${IMAGE_REPO_NAME}:dependency
        --build-arg BUILDKIT_INLINE_CACHE=1
        --tag ${IMAGE_REPO_NAME}:latest
        .
      - docker tag ${IMAGE_REPO_NAME}:latest ${PUBLIC_ECR_URL}/${IMAGE_REPO_NAME}:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${PUBLIC_ECR_URL}/${IMAGE_REPO_NAME}:latest
